loadJSONP({
    "computer": "der Computer",
    "appointmnt": "die Verabredung",
    "hobby": "das Hobby",
    "friend (male)": "der Freund",
    "friend (female)": "die Freundin",
    "book": "das Buch",
    "soccer": "der Fußball",
    "people": "die Leute",
    "cafe": "das Café",
    "doctor (male)": "der Arzt",
    "music": "die Musik",
    "cinema": "das Kino",
    "hairdresser": "der Friseur",
    "doctor (female)": "die Ärztin",
    "theater": "das Theater",
    "journalist": "der Journalist",
    "craftswoman": "die Handwerkerin",
    "museum": "das Museum",
    "chef": "der Koch",
    "waitress": "die Kellnerin",
    "swimming pool": "das Schwimmbad",
    "nurse": "der Krankenpfleger",
    "cook (female)": "die Köchin",
    "photo": "das Foto",
    "colleague (male)": "der Kollege",
    "colleague (female)": "die Kollegin",
    "hospital": "das Krankenhaus",
    "teacher": "der Lehrer",
    "company": "die Firma",
    "restaurant": "das Restaurant",
    "course": "der Kurs",
    "school": "die Schule",
    "seminar": "das Seminar",
    "policeman": "der Polizist",
    "mechanic (female)": "die Mechanikerin",
    "taxi": "das Taxi",
    "taxi driver": "der Taxifahrer",
    "student (female)": "die Studentin",
    "car": "das Auto",
    "evening": "der Abend",
    "saleswoman": "die Verkäuferin",
    "weekend": "das Wochenende",
    "afternoon": "der Nachmittag",
    "hour": "die Stunde",
    "year": "das Jahr",
    "moment": "der Moment",
    "week": "die Woche",
    "birth date": "das Geburtsdatum",
    "day": "der Tag",
    "information": "die Information",
    "form": "das Formular",
    "weekday": "der Wochentag",
    "address": "die Adresse",
    "example": "das Beispiel",
    "appointment": "der Termin",
    "street": "die Straße",
    "dictionary": "das Wörterbuch",
    "family name": "der Familienname",
    "house number": "die Hausnummer",
    "room": "das Zimmer",
    "place of residence": "der Wohnort",
    "postal code": "die Postleitzahl",
    "place of birth": "der Geburtsort",
    "note": "die Notiz",
    "key": "der Schlüssel"
     });