loadJSONP({
    "Mensch": "der Mensch",
    "Fahrrad": "das Fahrrad",
    "Bus": "der Bus",
    "Haus": "das Haus",
    "Rathaus": "das Rathaus",
    "Straßenbahn": "die Straßenbahn",
    "Zug": "der Zug",
    "Konzerthaus": "das Konzerthaus",
    "U-Bahn": "die U-Bahn",
    "Kirche": "die Kirche",
    "S-Bahn": "die S-Bahn",
    "Turm": "der Turm",
    "Schiff": "das Schiff",
    "Hotel": "das Hotel",
    "Flugzeug": "das Flugzeug",
    "Brücke": "die Brücke",
    "Fahrkarte": "die Fahrkarte",
    "Park": "der Park",
    "schnell": "schnell",
    "Markt": "der Markt",
    "nach": "nach",
    "Bahnhof": "der Bahnhof",
    "Hafen": "der Hafen",
    "See": "der See",
    "einen Weg beschreiben": "einen Weg beschreiben",
    "Fluss": "der Fluss",
    "Weg": "der Weg",
    "Meer": "das Meer",
    "Wo ist bitte": "Wo ist bitte",
    "sehen": "sehen",
    "Das ist ganz einfach": "Das ist ganz einfach",
    "rechts": "rechts",
    "da": "da",
    "links": "links",
    "Das ist": "Das ist",
    "geradeaus": "geradeaus",
    "interessant": "interessant",
    "schon": "schon",
    "Gehen Sie zuerst rechts und dann geradeaus": "Gehen Sie zuerst rechts und dann geradeaus",
    "Station": "die Station",
    "richtig": "richtig",
    "Ort": "der Ort",
    "genau": "genau",
    "Maße angeben": "Maße angeben",
    "Mitte": "die Mitte",
    "Wo ist das? - Genau in der Mitte": "Wo ist das? - Genau in der Mitte",
    "Meter": "der Meter",
    "also": "also",
    "Kilometer": "der Kilometer",
    "lang": "lang",
    "zeigen": "zeigen",
    "breit": "breit",
    "Plan": "der Plan",
    "zeichnen": "zeichnen",
    "hoch": "hoch",
    "Start": "der Start",
    "Ziel": "das Ziel",
    "über": "über",
    "Kosten": "die Kosten",
    "Euro": "der Euro",
    "Event": "das Event",
    "Festival": "das Festival",
    "zu Fuß gehen": "zu Fuß gehen",
    "Ticket": "das Ticket"
});
